[docs] Add example for the behat generators tool
moodle/devdocs pull request #1013
Opened 2024-05-07 10:00 UTC by sarjona

2024-05-10 05:14 UTC, andrewnicols requested changes

2024-05-10 05:14 UTC, andrewnicols commented on general/development/tools/generator.md
> +An example Behat generator file can be found in the directory [`admin/tool/generator/tests/fixtures/`](https://github.com/moodle/moodle/blob/main/admin/tool/generator/tests/fixtures/). For instance,
```suggestion
Some example Behat generator files can be found in [`admin/tool/generator/tests/fixtures/`](https://github.com/moodle/moodle/blob/main/admin/tool/generator/tests/fixtures/). For instance, [`testscenario/scenario.feature`](https://github.com/moodle/moodle/blob/main/admin/tool/generator/tests/fixtures/testscenario/scenario.feature) creates a course with two assignment activities and enrols one teacher along with five students.
```

2024-05-10 05:30 UTC, sarjona commented
Hi @andrewnicols!
Thanks a lot for reviewing and improving the patch. I've added your suggestions and rebased the branch to the latest <3

2024-05-12 15:53 UTC, andrewnicols approved these changes

2024-05-12 15:53 UTC, merged