Devdocs bootstrap theme color level
moodle/devdocs pull request #1037
Opened 2024-06-04 06:56 UTC by laurentdavid

[devdoc] Devdocs Bootstrap theme-color-level refactor

2024-06-13 09:00 UTC, roland04 requested changes
Thanks a lot for writing this doc page.
Because it is blocked by https://github.com/moodle/devdocs/pull/1037/commits/22ed6bb2cee06097c2890bf4a035332c10e0a5a5, I'd note that in the description.
I'd also note that it is related to [MDL-81816](https://tracker.moodle.org/browse/MDL-81816) tracker issue.
Thanks Laurent, hope it helps!

2024-06-17 06:55 UTC, laurentdavid commented on docs/guides/bs5migration/index.md
> +```
Thanks. You are right. Done !

2024-06-17 06:55 UTC, laurentdavid commented on docs/guides/bs5migration/index.md
> +    ...
Done !

2024-06-17 06:55 UTC, laurentdavid commented on docs/guides/bs5migration/index.md
> +In the stable 5.0 the final decision was to adopt `shift-color()` so we will use this function in the bridge file.
Ok. Used notes. Looks better. Thanks !

2024-08-19 07:10 UTC, roland04 approved these changes

2024-09-11 09:36 UTC, aanabit approved these changes
The documentation seems fine to me and explains the changes and the new approach.

2024-09-13 14:35 UTC, merged