[docs] Make clear that sesskey is CSRF token.
moodle/devdocs pull request #1083
Opened 2024-07-18 21:42 UTC by kabalin

`sesskey` is often confused with Moodle Session ID cookie. This change updates Session Key section at Cross-site request forgery page, clarifying its purpose as CSRF token.

2024-07-29 01:31 UTC, andrewnicols requested changes
Thanks for adding the clarification. Just a few tidyups.

2024-07-29 01:31 UTC, andrewnicols commented on general/development/policies/security/crosssite-request-forgery.md
> +When you log in, Moodle generates random string and stores it in the session. Whenever it prints a link or a button to perform a significant action, it adds the sesskey value to the submitted data. B
```suggestion
When you log in, Moodle generates a random string and stores it in the session. Whenever it prints a link or a button to perform a significant action, it adds the sesskey value to the submitted data. Before performing the action, it checks the sesskey value in the request with the one in the session, and the action is only performed if the two match.
```

2024-07-29 01:31 UTC, andrewnicols commented on general/development/policies/security/crosssite-request-forgery.md
> +**sesskey** should not be confused with Moodle Session ID, which a PHP session cookie responsible for session continuity (remaining logged in).
```suggestion
The `sesskey` should not be confused with Moodle Session ID, which a PHP session cookie responsible for session continuity (remaining logged in).
```

2024-07-29 01:31 UTC, andrewnicols commented on general/development/policies/security/crosssite-request-forgery.md
> +The most important protection is the concept CSRF token, which is for historic reasons called **sesskey** in Moodle.
```suggestion
The most important protection is the concept CSRF token, which is for historic reasons called **`sesskey`** in Moodle.
```

2024-07-29 14:27 UTC, kabalin commented
> Thanks for adding the clarification. Just a few tidyups.

Thanks Andrew!

2024-08-08 19:03 UTC, kabalin commented
Squashed Andrews's improvements and rebased.

2024-08-09 12:28 UTC, merged