Next release
moodle/devdocs pull request #1150
Opened 2024-10-08 04:20 UTC by andrewnicols

This commit adds the following changes:
- a new version management script to make modifying the versions.json far easier
- a fix for some 1.9 version data
- the next set of release information for each branch

2024-10-09 05:31 UTC, junpataleta requested changes
Thanks, @andrewnicols! The version script is really handy! 

It just needs some minor changes from my review comments.

I'd also suggest we document this script either as part of
- [Task 9 (release notes task) of the 1 week prior](https://moodledev.io/general/development/process/release#1-week-prior) release tasks
- [Task 4 of the Release day tasks](https://moodledev.io/general/development/process/release#release-day).

What do you think?

2024-10-09 05:31 UTC, junpataleta commented on scripts/version.mjs
> +        message: 'What is the expected release date?',
It might be good to specify acceptable date formats.

2024-10-09 05:31 UTC, junpataleta commented on scripts/version.mjs
> +        message: 'What is the general support end date?',
Should be "security support end date"

2024-10-09 12:15 UTC, andrewnicols commented
I've updated with the requested changes and improved the help for majors.

> I'd also suggest we document this script either as part of

I agree

> * [Task 9 (release notes task) of the 1 week prior](https://moodledev.io/general/development/process/release#1-week-prior) release tasks

Usually Mick is the one who does this. @mickhawkins which step do you do this in? We should try and document it.

> * [Task 4 of the Release day tasks](https://moodledev.io/general/development/process/release#release-day).
> 
> What do you think?
That step is already wrong. Again I think it's done by Mick about a day or two before a release when he does the release notes.

2024-10-10 05:43 UTC, junpataleta approved these changes
Thanks, Andrew! Looks good!

2024-10-10 05:43 UTC, merged