[docs] Migrate new features and ideas
moodle/devdocs pull request #200
Opened 2022-06-09 10:33 UTC by laurentdavid

Migrated pages :

* https://docs.moodle.org/dev/New_feature_ideas

Closes #173

2022-06-09 11:13 UTC, andrewnicols requested changes
Just a couple of minor things

2022-06-09 11:13 UTC, andrewnicols commented on general/community/contribute/new-features-ideas.md
> +- Community
Suggest adding some more tags, for example:

- Ideas
- Getting started

2022-06-09 11:13 UTC, andrewnicols commented on general/community/contribute/new-features-ideas.md
> +- Either join an existing discussion about your idea or start a new discussion in an appropriate [forum on moodle.org](http://moodle.org/course/view.php?id=5).
Suggest moving the link, and removing 'Either'

```suggestion
- Join an existing discussion about your idea, or start a new discussion in an [appropriate forum on moodle.org](http://moodle.org/course/view.php?id=5).
```

2022-06-09 11:13 UTC, andrewnicols commented on general/community/contribute/new-features-ideas.md
> +  The M in Moodle stands for modular, and so the easiest ideas for new developers to implement are new modules and plugins.
Take this line out - it's not true. Moodle has not been an acronym for 15 years. Perhaps re-word it?

2022-06-09 11:13 UTC, andrewnicols commented on sidebars/general.js
> +                    label: 'New ideas',
Not sure about the naming for this. Maybe 'Suggesting features'

2022-06-14 03:15 UTC, andrewnicols commented
I'm converting this back to a draft because we discussed that it may be better to merge this into another page as this one does not really offer very much.

2024-04-25 05:28 UTC, sarjona approved these changes
Hi @laurentdavid!
Thanks for helping with the migration of this page. I agree that merging it with the current Contributing page makes sense and, although I'm not sure if having all the information as an admonition is the best way to display it, I'm happy to merge it and see what other people think about it :-)

2024-04-25 05:31 UTC, merged