[docs] Migrate Output API and Output functions
moodle/devdocs pull request #216
Opened 2022-06-13 11:13 UTC by kabalin

Migrated pages:
- https://docs.moodle.org/dev/Output_API
- https://docs.moodle.org/dev/Output_functions

Closes #179

2022-06-13 12:51 UTC, andrewnicols requested changes
I don't have a chance to finish a review now as I'm done for the day, but I have a couple of notes so far.

2022-06-13 12:51 UTC, andrewnicols commented on docs/apis/subsystems/output.md
> +## Overview
I'd recommend taking this out. We've standardised to remove the first title if it's something like "Introduction", or "Overview". There is no benefit.

2022-06-13 12:51 UTC, andrewnicols commented on docs/apis/subsystems/output.md
> +
```suggestion
```

2022-06-13 12:51 UTC, andrewnicols commented on docs/apis/subsystems/output.md
> +:::
This is largely irrelevant to the Output API docs.

I'd suggest putting it into a collapsed `<details>` section or an `:::info` section, for example:

```suggestion
:::info Setup of an admin page

On admin pages the `admin_externalpage_setup($sectionname);` function should be used to setup and perform permission checks, for example:

```php title="admin/tool/demo/mypage.php"
require_once(__DIR__ . '/../../config.php');
require_once("{$CFG->libdir}/adminlib.php");

admin_externalpage_setup('example');
```

:::

```

I'd suggest detailing the PAGE API still, but with more info.

2022-06-13 14:01 UTC, andrewnicols commented
Oh, I meant to say, once you've rebasd you'll need to run:

```yarn mdfix-all ; yarn mdxfix-all```

That will update any reference to the migrated docs. It will become a part of the mgiration script when #207 lands but for now it's a manual process.

2022-06-13 15:03 UTC, kabalin commented
Thanks @andrewnicols , I addressed all the comments and fixed the cross-links. Not sure if I got your suggestion about `PAGE` correctly, please comment if more changes are needed.

2022-06-14 03:13 UTC, andrewnicols approved these changes
Looks good to me.

There's always going to be improvements that we can make here, but I think that they can happen _after_ we get documents migrated now.

2022-06-14 03:14 UTC, merged