Meeting recording now available
moodle/devdocs pull request #226
Opened 2022-06-14 12:37 UTC by wildgirl

2022-06-14 14:17 UTC, andrewnicols commented
Hi Helen,

Are we able to use the link directly:

https://moodle.org/mod/bigbluebuttonbn/bbb_view.php?action=play&bn=1&rid=19&rtype=video

2022-06-14 14:51 UTC, sarjona submitted a review, later dismissed
Helen, thanks for updating the recording for today's session :-)

2022-06-14 14:56 UTC, sarjona requested changes
Hi Helen! As you'll see, there is an empty space at the end of a line that should be removed :-)

2022-06-14 14:56 UTC, sarjona commented on general/community/meetings/202206.md
> +Tuesday 14 June 2022 at 08:00 UTC
```suggestion
Tuesday 14 June 2022 at 08:00 UTC
```

2022-06-15 01:50 UTC, andrewnicols approved these changes

2022-06-15 01:51 UTC, merged

2022-06-15 05:39 UTC, wildgirl commented
> Hi Helen,
> 
> Are we able to use the link directly:
> 
> https://moodle.org/mod/bigbluebuttonbn/bbb_view.php?action=play&bn=1&rid=19&rtype=video

Good suggestion Andrew, that would be much better.