[Docs] Migrate Time API
moodle/devdocs pull request #275
Opened 2022-07-03 13:15 UTC by Chocolate-lightning

2022-07-05 02:48 UTC, andrewnicols commented
Did you forget to check in the migrated page? I only see the migratedPages.yml file, and the fixed references to it.

2022-07-05 03:17 UTC, Chocolate-lightning commented
Heh, oh my, that is a bit embarrassing. It seems my brain fell out on the floor as I was committing the changes. Checking now I have attached the file...

2022-07-05 14:24 UTC, andrewnicols requested changes
A couple of minor things and this is good to go.

2022-07-05 14:24 UTC, andrewnicols commented on docs/apis/subsystems/time/index.md
> +echo userdate($date->getTimestamp());
```suggestion
```php
$date = new DateTime();
$date->setTimestamp(intval($unixtime);
echo userdate($date->getTimestamp());
```
```

2022-07-06 04:33 UTC, andrewnicols approved these changes

2022-07-06 04:34 UTC, merged