Customfields API
moodle/devdocs pull request #311
Opened 2022-07-17 12:31 UTC by aya-saad1

Migrate Customfields API

2022-07-18 06:05 UTC, andrewnicols requested changes
Hi Aya,

Thanks for making this change. There are a few extra changes here which are not correct and make it harder to see the actual changes (plugin-names.txt, and project-words.txt).

Additionally this file probably should be broken into two separate pages. With this new documentation we're trying to make the distinction between how to _use_ the subsystem, and how to write a plugin clearer so that developers can find the information relevant to them.

If you're able to make some of these changes then that would be great, otherwise please let us know and we can update your pull request to make the changes and move the rest of the notes to a followup issue.

2022-09-06 18:21 UTC, wojtekxtx commented on docs/apis/customfields/index.md
> +  1. Custom fields API overview
@andrewnicols no, it should not

2022-09-06 18:23 UTC, wojtekxtx commented on docs/apis/customfields/index.md
> +---
@andrewnicols if both are valid than everything is ok here

2022-09-06 18:24 UTC, wojtekxtx commented on project-words.txt
> -# This file contains cspell exceptions to use for Moodle.
> What are all of these changes?

Really @andrewnicols ?

2022-09-06 18:24 UTC, wojtekxtx commented on docs/apis/customfields/index.md
> +Custom fields API does not export or delete any data because it does not know how custom fields are used, what data is considered user data and if it is considered private or shared data.
@andrewnicols go back to elementary school and relearn language basics.

2022-09-06 18:26 UTC, wojtekxtx commented on docs/apis/customfields/index.md
> +Custom fields API was added in Moodle 3.7. It allows to configure custom fields that can be added to various contexts. Each **component** (or plugin) that wants to use custom fields can define severa
@andrewnicols Id suggest you just stop what you are doing, and everyone will be fine!

2022-09-06 18:28 UTC, wojtekxtx commented on docs/apis/customfields/index.md
> +  1. How to use custom fields
will repeat: first learn grammar than correct whats already correct!

2022-09-06 18:29 UTC, wojtekxtx commented on docs/apis/customfields/index.md
> +Component/plugin that uses custom fields must define a **handler class** for each area and a **configuration page**. Handler class must be called **PLUGINNAME/customfield/AREA_handler** and be placed
@andrewnicols NO. Break it yourself if you really want it to be broken. Or, better, just fuck off.

2022-10-18 09:20 UTC, sarjona commented
Hi dear @aya-saad1! Is there any chance you can review the points raised by Andrew? Thanks in advance for your help!! :-*

2024-04-24 06:15 UTC, sarjona commented
I'm closing this pull-request on Aya's behalf after asking her if she was planning to improve the patch and send it back to review.

2024-04-24 06:15 UTC, closed without merging