Update PHP Markdown in thirdpartylibs
moodle/devdocs pull request #405
Opened 2022-10-25 04:40 UTC by davewoloszyn

2022-10-25 06:57 UTC, sarjona requested changes
Hi @davewoloszyn!
Thanks for updating the thirdpartylibs page. Well done! As you'll see, a minor change is required (to improve it).
Please, remember to send it back to review once you update the patch :-)

2022-10-25 06:57 UTC, sarjona commented on general/community/credits/thirdpartylibs.md
> +**Version**: 2.0.0 (with modifications)<br/>
```suggestion
**Version**: 2.0.0<br/>
```

2022-10-25 06:57 UTC, sarjona commented on general/community/credits/thirdpartylibs.md
> +**Version**: 2.0.0 (with modifications)<br/>
I think we can remove the (with modifications) part because looking a the readme_moodle.txt there are no modifications anymore ;-)

2022-10-25 23:39 UTC, davewoloszyn commented
Hi Sara, I have updated the patch as requested. I can't find anywhere to remove the 'waiting-for-feedback' label. Any ideas?

2022-10-26 06:27 UTC, sarjona approved these changes
Hi David! 
Thanks for updating the patch! It looks great!! Let's see if you can see the labels once you get your first issue integrated ;-)

2022-10-26 06:27 UTC, merged