Add Font Awesome 6 to devupdate (blocked by MDL-76989)
moodle/devdocs pull request #569
Opened 2023-03-06 11:39 UTC by sarjona

A reference to the devupdate page for Moodle 4.2 should be added to mention Font Awesome has been upgraded from 4.7 to 6.3.0 in [MDL-76989](https://tracker.moodle.org/browse/MDL-76989).

2023-03-07 05:29 UTC, andrewnicols requested changes

2023-03-07 05:29 UTC, andrewnicols commented on docs/devupdate.md
> +Font Awesome 6 is backwards compatible (because shim has been included too), so the old syntax is still working.
minor grammar: 

```suggestion
Font Awesome 6 is backwards compatible (because a shim has been included too), so the old syntax still works.
```

2023-03-07 05:29 UTC, andrewnicols commented on docs/devupdate.md
> +More information about the changes between 4 and 6, like the icons that have been renamed, can be found in https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4
```suggestion
More information about the changes between 4 and 6, including any icons which have been renamed, can be found in https://fontawesome.com/docs/web/setup/upgrade/upgrade-from-v4
```

2023-03-07 07:59 UTC, sarjona commented
Hi @andrewnicols!
Thanks a lot for reviewing the patch and suggesting these improvements in the wording! <3 I appreciate it a lot! :-*

2023-03-07 08:50 UTC, andrewnicols commented
Holding off on merge ubtil 76989 lands.

As a side-note, it would be super if we could add a GHA check of some kind to have it block until the issue lands, at which point it auto merges.

No: CI Lint is failing here.

2023-03-07 08:59 UTC, sarjona commented
Thanks Andrew!

The lint errors are unrelated to this page. I've created a PR to fix them: https://github.com/moodle/devdocs/pull/571

I love the idea of the GHA job to block issues until they land (although for now, I think that's something that can be done manually by integrators when we merge the issue).

2023-03-16 15:07 UTC, sarjona commented
I've added more information to explain some more changes that developers might need to apply to their code.

2023-03-20 10:37 UTC, sarjona commented
Now that [MDL-76989](https://tracker.moodle.org/browse/MDL-76989) has been integrated, it would be great having this merged too :-)

2023-03-20 10:39 UTC, sarjona commented
@andrewnicols could you take a look at the changes I added last week (after you reviewed it) :-)

2023-03-28 09:21 UTC, merged