[repo] Create a basic fetch script
moodle/devdocs pull request #63
Opened 2022-04-20 16:05 UTC by andrewnicols

This is a really basic system to fetch a page from the legacy docs into
a new location on disk, and perform basic changes.

It does *NOT* catch everything and it can do better, but it's what I've
been doing manually.

At the moment it will:

- not convert any table
- complain about migrated pages but not fix them
- do nothing with tracker links

I've tried to merge some of the functions and utilities that I
previously wrote for the legacy wiki updater into a shared utils file
too.

2022-04-21 05:23 UTC, andrewnicols commented
Rewritten to:

```
node scripts/wikimedia-fetch.js migrate Authentication_plugins docs/apis/plugintypes/auth.md
```

2022-04-21 06:55 UTC, sarjona commented on scripts/wikimedia-fetch.js
> +        title: title.replace('_', ' '),
replaceAll should be used (because sometimes titles have more than one '_'

2022-04-21 12:21 UTC, sarjona requested changes

2022-04-27 19:50 UTC, sarjona approved these changes

2022-04-27 19:50 UTC, merged