Update tracker.md
moodle/devdocs pull request #672
Opened 2023-06-28 12:19 UTC by timhunt

As discussed in dev chat, write down the formerly unwritten rule that you should always add a comment to explain what you are doing when editing tracker issues.

2023-06-28 12:35 UTC, paulholden requested changes

2023-06-28 14:37 UTC, andrewnicols approved these changes

2023-06-28 14:41 UTC, andrewnicols commented
Unfortunately we can't squash in the UI for some reason when the Merge queue is enabled.

2023-07-01 09:52 UTC, paulholden approved these changes

2023-07-03 14:09 UTC, closed without merging