Expanded DB identifier sizes (tables and columns - MDL-76459)
moodle/devdocs pull request #728
Opened 2023-09-10 14:45 UTC by stronk7

Update all the references to the old 28 and 30 char long limits to the new 53 and 63 ones for Moodle 4.3 and up.

2023-09-11 01:04 UTC, andrewnicols requested changes
I'd also suggest noting this in the `docs/devupdate.md` page with an appropriate note reminding devs about older version support too.

2023-09-11 01:04 UTC, andrewnicols commented on docs/apis/plugintypes/assign/feedback.md
```suggestion

Note: If your plugin is intended to work with versions of Moodle older than 4.3, then the plugin name must be 13 characters or shorter, and table names must be 28 characters or shorter.
```

2023-09-11 01:04 UTC, andrewnicols commented on docs/apis/plugintypes/assign/submission.md
>  :::
```suggestion

Note: If your plugin is intended to work with versions of Moodle older than 4.3, then the plugin name must be 11 characters or shorter, and table names must be 28 characters or shorter.
```

2023-09-11 01:04 UTC, andrewnicols commented on general/development/tools/xmldb.md
> +    1. Table names and field names must use only a-z, 0-9 and _ chars. Max 53 characters for tables and 63 characters for fields (28 and 30 before Moodle 4.3).
```suggestion
    1. Table names and field names must use only a-z, 0-9 and _ chars. Max 53 characters for tables and 63 characters for fields (28 and 30 before Moodle 4.3).

     :::caution
     
     If you are writing a plugin intended for older versions of Moodle then you must continue to use the lower limits of 28, and 30.
     :::
```

2023-09-11 08:20 UTC, stronk7 commented
Thanks for the review @andrewnicols ,

1. have accepted all your suggestions.
2. Now will fetch the changes locally and rebase & squash.
3. Will add the information to `docs/devupdate.md`, as suggested. I remember I thought about it yesterday, but somehow missed it.

Ciao :-)

2023-09-11 08:53 UTC, stronk7 commented
Fun fact, I had a typo with `previous`, written as `pervious` that is a valid word (now learnt).

I've now forced-pushed the branch to fix that.

2023-09-12 05:12 UTC, andrewnicols approved these changes

2023-09-12 05:12 UTC, merged