Meta enrolment in csv course upload
moodle/devdocs pull request #815
Opened 2023-11-17 02:12 UTC by ilyatregubov

MDL-73852 changes

2023-12-01 06:37 UTC, sarjona requested changes
Hi @ilyatregubov!
Thanks a lot for preparing a patch for this. As you'll see, I added a few minor proposals to improve it :-)

2023-12-01 06:37 UTC, sarjona commented on docs/devupdate.md
> +## Meta enrolment support in csv course upload
```suggestion
## Enrolment

### Meta enrolment support in CSV course upload
```

2023-12-01 06:37 UTC, sarjona commented on docs/devupdate.md
>  ## Multiple enrol instances of same type in csv course upload
```suggestion
### Multiple enrol instances of same type in CSV course upload
```

2023-12-01 06:37 UTC, sarjona commented on docs/devupdate.md
> +It is now possible to use meta enrolment when uploading courses using CSV file. Here is an example of csv file that can be used to upload a course with meta enrolment:
```suggestion
It is now possible to use meta enrolment when uploading courses using CSV file. Here is an example of CSV file that can be used to upload a course with meta enrolment:
```

2023-12-01 06:37 UTC, sarjona commented on docs/devupdate.md
> +```php
```suggestion
```php title="Example of CSV for meta enrolment"
```

2024-04-22 06:48 UTC, ilyatregubov commented
All issues have been resolved. Just need someone to approve

2024-04-22 15:03 UTC, sarjona approved these changes
Hi @ilyatregubov!
Thanks for reviewing the patch. I'm happy to approve and merge it. Well done!

2024-04-22 15:03 UTC, merged