Start documenting core_question and qbank_
moodle/devdocs pull request #907
Opened 2024-02-26 15:24 UTC by timhunt

Fully documenting core_question and all the related plugin types is going to be a mammoth task 🦣🦣🦣.

But a journey of a thousand miles starts with a single step, or some other trite cliche, so here is one.

All this because I wanted to explain newquestiondefaults.md in MDL-79863 - and it was obviously better to do that in the dev docs than a tracker comment, and I needed to build a framework to put that in.

2024-02-27 02:36 UTC, andrewnicols requested changes
Hi Tim,

This is great! I love it and I'm so pleased to see some documentation for this.

I've added quite a few  comments here, but many are just typos, etc.

There are a few other things that I have commented in a few places but not everywhere:
- we typically put component names in backticks
- [admonitions](https://docusaurus.io/docs/next/markdown-features/admonitions) are a great feature and help useful or important information stand out
- we have tried to avoid use of abbreviations like `i.e.` and `e.g.` based on advice in developer documentation guides from both MS and Google.
- we have tried to follow both of these guides but we have not formally adopted either. They are both worth consulting though and have some really good advice on writing clear docs.

Thanks,

Andrew

2024-02-27 02:36 UTC, andrewnicols commented on docs/apis/plugintypes/qtype/newquestiondefaults.md
> +because these are things that make a particular question what it is, and will alwasy be different. So, we only want to
```suggestion
because these are things that make a particular question what it is, and will always be different. So, we only want to
```

2024-02-27 02:36 UTC, andrewnicols commented on docs/apis/plugintypes/qtype/newquestiondefaults.md
> +Before implementing this feature, your form class is likely to have code like
```suggestion
Before implementing this feature, your form class is likely to have code which sets defaults, for example:
```

2024-02-27 18:34 UTC, timhunt commented on docs/apis/plugintypes/qbank/index.md
> +Question bank plugins allow you to extend the functionality of the Moodle Question bank. They just one of the plugin
The questoin is, can I persaude my editor to word-wrap the display of just .md? I was only doing this so I could read what I was writing. Yes, foudn the right PHPstorm config.

2024-02-27 18:46 UTC, timhunt commented
Thanks for the feedback Andrew. I considered all you comments even if I ingored some.

2024-03-11 12:11 UTC, timhunt commented
I just reviewed everything, and made various amends. Hopefully this is now in a good enough state to land, so I can move on to part 2.

2024-03-26 13:40 UTC, merged

2024-03-26 13:41 UTC, andrewnicols commented
Thanks Tim,

Sorry for the delay. I'm going to land this today and we can work on improving it as more parts land.