4.5 dates
moodle/devdocs pull request #980
Opened 2024-04-22 03:06 UTC by andrewnicols

2024-04-22 03:07 UTC, andrewnicols commented
Dates pulled from the product heartbeat. I think I have the correct dates for end of support too.

2024-04-22 05:34 UTC, sarjona requested changes

2024-04-22 05:34 UTC, sarjona commented on src/components/ReleaseTable/index.tsx
Hi @andrewnicols!
Thanks for working on this. The changes look good but I'm not sure about this one because, although I find it useful having when the next minor will be released for each Moodle version... Is there any other reason to hide this information from users? Otherwise, I'll suggest leaving it as it is now (because I know it helps people to find the dates).

2024-04-23 05:33 UTC, sarjona approved these changes
Hi @andrewnicols!
Thanks for removing the commit to hide the next releases :-)
The patch looks great and it's working as expected ;-)

2024-04-23 05:34 UTC, merged